package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"errors"
	"hackbar-copilot/internal/interface-adapter/handler/graphql/graph/model"
)

// Checkout is the resolver for the checkout field.
func (r *mutationResolver) Checkout(ctx context.Context, input model.InputCheckout) (*model.Checkout, error) {
	_, err := r.authAdapter.GetEmail(ctx)
	if /* unauthorized */ err != nil {
		return nil, err
	}
	if !r.authAdapter.HasBartenderRole(ctx) {
		return nil, errors.New("forbidden")
	}

	customerEmail, orderIDs, diffs, paymentType, err := inputCheckout(input).apply()
	if err != nil {
		return nil, err
	}

	c, err := r.Cashier.Checkout(customerEmail, orderIDs, diffs, paymentType)
	if err != nil {
		return nil, err
	}

	return checkout_(c).apply(), nil
}
