package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"
	"hackbar-copilot/internal/domain/order"
	"hackbar-copilot/internal/interface-adapter/handler/graphql/graph/model"
	"hackbar-copilot/internal/interface-adapter/handler/middleware"
)

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	jwtClaims, err := middleware.GetJWT(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized: %w", err)
	}

	// TODO: Switch by permission
	// orders, err := r.Copilot.LatestOrders()

	orders, err := r.OrderService.ListOrders(order.CustomerID(jwtClaims.Email))
	if err != nil {
		return nil, fmt.Errorf("failed to list orders: %w", err)
	}

	return r.orderAdapter.Orders(orders), nil
}
