package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"hackbar-copilot/internal/interface-adapter/handler/graphql/graph/model"
	"hackbar-copilot/internal/usecase/copilot"
)

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context) ([]*model.RecipeGroup, error) {
	recipeGroups, err := r.Copilot.ListRecipes(copilot.SortRecipeGroupByName())
	if err != nil {
		return nil, err
	}
	recipeTypes, err := r.Copilot.FindRecipeType()
	if err != nil {
		return nil, err
	}
	glassTypes, err := r.Copilot.FindGlassType()
	if err != nil {
		return nil, err
	}
	return r.recipeAdapter.RecipeGroups(recipeGroups, recipeTypes, glassTypes), nil
}
