package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"hackbar-copilot/internal/interface-adapter/handler/graphql/graph/model"
)

// SaveRecipe is the resolver for the saveRecipe field.
func (r *mutationResolver) SaveRecipe(ctx context.Context, input model.InputRecipeGroup) (*model.RecipeGroup, error) {
	recipeGroup, err := r.deps.Recipes.Register(input)
	if err != nil {
		return nil, err
	}
	recipeTypes, err := r.deps.Recipes.FindRecipeType()
	if err != nil {
		return nil, err
	}
	glassTypes, err := r.deps.Recipes.FindGlassType()
	if err != nil {
		return nil, err
	}
	return r.deps.convertToModel.RecipeGroup(recipeTypes, glassTypes)(recipeGroup), nil
}
