package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"hackbar-copilot/internal/domain/order"
	"hackbar-copilot/internal/interface-adapter/handler/graphql/graph/model"
)

// UserInfo is the resolver for the user field.
func (r *queryResolver) UserInfo(ctx context.Context) (*model.User, error) {
	email, err := r.authAdapter.GetEmail(ctx)
	if /* unauthorized */ err != nil {
		return nil, err
	}

	// TODO: Get user info from JWT claims. (e.g. github id)

	user, err := r.OrderService.GetUserInfo(order.CustomerEmail(email))
	if err != nil {
		return nil, err
	}

	return userAdapter(user).apply(), nil
}
